// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: select.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const extractBooksForEmbedding = `-- name: ExtractBooksForEmbedding :many
SELECT
    isbn,
    title,
    description,
    toc,
    recommendation
FROM books b
WHERE (
        b.vector_search is false
        and b.source is not null
        AND (
            ISBN LIKE '97911%'
            OR ISBN LIKE '97889%'
            OR ISBN LIKE '97989%'
        )
    )
LIMIT 30000
`

type ExtractBooksForEmbeddingRow struct {
	Isbn           pgtype.Text
	Title          pgtype.Text
	Description    pgtype.Text
	Toc            pgtype.Text
	Recommendation pgtype.Text
}

func (q *Queries) ExtractBooksForEmbedding(ctx context.Context) ([]ExtractBooksForEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, extractBooksForEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExtractBooksForEmbeddingRow
	for rows.Next() {
		var i ExtractBooksForEmbeddingRow
		if err := rows.Scan(
			&i.Isbn,
			&i.Title,
			&i.Description,
			&i.Toc,
			&i.Recommendation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooks = `-- name: GetBooks :many
SELECT id, isbn, title, author, publisher, publication_year, volume, image_url, description, recommendation, toc, source, url, vector_search FROM Books
`

func (q *Queries) GetBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.PublicationYear,
			&i.Volume,
			&i.ImageUrl,
			&i.Description,
			&i.Recommendation,
			&i.Toc,
			&i.Source,
			&i.Url,
			&i.VectorSearch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksFromIsbn = `-- name: GetBooksFromIsbn :one
SELECT id, isbn, title, author, publisher, publication_year, volume, image_url, description, recommendation, toc, source, url, vector_search FROM Books WHERE isbn = $1
`

func (q *Queries) GetBooksFromIsbn(ctx context.Context, isbn pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBooksFromIsbn, isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Publisher,
		&i.PublicationYear,
		&i.Volume,
		&i.ImageUrl,
		&i.Description,
		&i.Recommendation,
		&i.Toc,
		&i.Source,
		&i.Url,
		&i.VectorSearch,
	)
	return i, err
}

const getBooksWithoutSource = `-- name: GetBooksWithoutSource :many
SELECT isbn
FROM Books
WHERE
    source is null
    AND (
        ISBN LIKE '97911%'
        OR ISBN LIKE '97889%'
        OR ISBN LIKE '97989%'
    )
ORDER BY isbn ASC
LIMIT 11000
`

func (q *Queries) GetBooksWithoutSource(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getBooksWithoutSource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var isbn pgtype.Text
		if err := rows.Scan(&isbn); err != nil {
			return nil, err
		}
		items = append(items, isbn)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksWithoutToc = `-- name: GetBooksWithoutToc :many
SELECT isbn
FROM Books
WHERE (source IN ('naver', 'daum'))
    AND (
        ISBN LIKE '97911%'
        OR ISBN LIKE '97889%'
        OR ISBN LIKE '97989%'
    )
    AND toc IS NULL
ORDER BY isbn ASC
`

func (q *Queries) GetBooksWithoutToc(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getBooksWithoutToc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var isbn pgtype.Text
		if err := rows.Scan(&isbn); err != nil {
			return nil, err
		}
		items = append(items, isbn)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibCodFromLibName = `-- name: GetLibCodFromLibName :one
SELECT lib_code FROM libraries WHERE lib_name = $1
`

func (q *Queries) GetLibCodFromLibName(ctx context.Context, libName pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLibCodFromLibName, libName)
	var lib_code pgtype.Text
	err := row.Scan(&lib_code)
	return lib_code, err
}

const searchFromBooks = `-- name: SearchFromBooks :many
SELECT id, isbn, title, author, publisher, publication_year, volume, image_url, description, recommendation, toc, source, url, vector_search
FROM books
WHERE
    author LIKE '%$1%'
    OR title LIKE '%$1%'
ORDER BY (
        (
            bigm_similarity (author, $1) + bigm_similarity (title, $1)
        ) * 10
    ) DESC
limit 50
`

func (q *Queries) SearchFromBooks(ctx context.Context, bigmSimilarity interface{}) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchFromBooks, bigmSimilarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.PublicationYear,
			&i.Volume,
			&i.ImageUrl,
			&i.Description,
			&i.Recommendation,
			&i.Toc,
			&i.Source,
			&i.Url,
			&i.VectorSearch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
