// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertLibraries implements pgx.CopyFromSource.
type iteratorForInsertLibraries struct {
	rows                 []InsertLibrariesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLibraries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLibraries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LibCode,
		r.rows[0].LibName,
		r.rows[0].LibAddress,
		r.rows[0].Tel,
		r.rows[0].Latitude,
		r.rows[0].Longtitude,
		r.rows[0].Homepage,
		r.rows[0].Closed,
		r.rows[0].OperatingTime,
		r.rows[0].BookCount,
	}, nil
}

func (r iteratorForInsertLibraries) Err() error {
	return nil
}

func (q *Queries) InsertLibraries(ctx context.Context, arg []InsertLibrariesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"libraries"}, []string{"lib_code", "lib_name", "lib_address", "tel", "latitude", "longtitude", "homepage", "closed", "operating_time", "book_count"}, &iteratorForInsertLibraries{rows: arg})
}
