// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID               int32
	Isbn             pgtype.Text
	Title            pgtype.Text
	Author           pgtype.Text
	Publisher        pgtype.Text
	Publicationyear  pgtype.Text
	Setisbn          pgtype.Text
	Additionalcode   pgtype.Text
	Volume           pgtype.Text
	Subjectcode      pgtype.Text
	Bookcount        pgtype.Int4
	Loancount        pgtype.Int4
	Registrationdate pgtype.Date
}

type Library struct {
	ID            int32
	Libcode       pgtype.Int4
	Libname       pgtype.Text
	Libaddress    pgtype.Text
	Tel           pgtype.Text
	Latitude      pgtype.Float8
	Longtitude    pgtype.Float8
	Homepage      pgtype.Text
	Closed        pgtype.Text
	Operatingtime pgtype.Text
	Bookcount     pgtype.Int4
}
