// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Book struct {
	ID              int32
	Isbn            pgtype.Text
	Title           pgtype.Text
	Author          pgtype.Text
	Publisher       pgtype.Text
	PublicationYear pgtype.Text
	Volume          pgtype.Text
	ImageUrl        pgtype.Text
	Description     pgtype.Text
	Recommendation  pgtype.Text
	Toc             pgtype.Text
	Source          pgtype.Text
	Url             pgtype.Text
	VectorSearch    pgtype.Bool
}

type Bookembedding struct {
	ID        int32
	Isbn      string
	Embedding pgvector.Vector
}

type Library struct {
	ID            int32
	LibCode       pgtype.Text
	LibName       pgtype.Text
	Address       pgtype.Text
	Tel           pgtype.Text
	Latitude      pgtype.Float8
	Longtitude    pgtype.Float8
	Homepage      pgtype.Text
	Closed        pgtype.Text
	OperatingTime pgtype.Text
}

type Libsbook struct {
	ID        int32
	LibCode   pgtype.Text
	Isbn      pgtype.Text
	ClassNum  pgtype.Text
	BookCode  pgtype.Text
	ShelfCode pgtype.Text
	ShelfName pgtype.Text
}
