// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBooks = `-- name: GetBooks :many
SELECT id, isbn, title, author, publisher, publicationyear, setisbn, additionalcode, volume, subjectcode, bookcount, loancount, registrationdate FROM Books
`

func (q *Queries) GetBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.Publicationyear,
			&i.Setisbn,
			&i.Additionalcode,
			&i.Volume,
			&i.Subjectcode,
			&i.Bookcount,
			&i.Loancount,
			&i.Registrationdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertBooksParams struct {
	Isbn             pgtype.Text
	Title            pgtype.Text
	Author           pgtype.Text
	Publisher        pgtype.Text
	Publicationyear  pgtype.Text
	Setisbn          pgtype.Text
	Additionalcode   pgtype.Text
	Volume           pgtype.Text
	Subjectcode      pgtype.Text
	Bookcount        pgtype.Int4
	Loancount        pgtype.Int4
	Registrationdate pgtype.Date
}

type InsertLibrariesParams struct {
	Libcode       pgtype.Int4
	Libname       pgtype.Text
	Libaddress    pgtype.Text
	Tel           pgtype.Text
	Latitude      pgtype.Float8
	Longtitude    pgtype.Float8
	Homepage      pgtype.Text
	Closed        pgtype.Text
	Operatingtime pgtype.Text
	Bookcount     pgtype.Int4
}
