// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateScrapData = `-- name: UpdateScrapData :exec
UPDATE Books
SET
    Description = $1,
    Recommendation = $2,
    Toc = $3,
    Source = $4,
    Url = $5
WHERE
    isbn = $6
`

type UpdateScrapDataParams struct {
	Description    pgtype.Text
	Recommendation pgtype.Text
	Toc            pgtype.Text
	Source         pgtype.Text
	Url            pgtype.Text
	Isbn           pgtype.Text
}

func (q *Queries) UpdateScrapData(ctx context.Context, arg UpdateScrapDataParams) error {
	_, err := q.db.Exec(ctx, updateScrapData,
		arg.Description,
		arg.Recommendation,
		arg.Toc,
		arg.Source,
		arg.Url,
		arg.Isbn,
	)
	return err
}

const updateVectorSearchStatus = `-- name: UpdateVectorSearchStatus :exec

UPDATE books SET vectorsearch = $1 WHERE isbn = $2
`

type UpdateVectorSearchStatusParams struct {
	Vectorsearch pgtype.Bool
	Isbn         pgtype.Text
}

func (q *Queries) UpdateVectorSearchStatus(ctx context.Context, arg UpdateVectorSearchStatusParams) error {
	_, err := q.db.Exec(ctx, updateVectorSearchStatus, arg.Vectorsearch, arg.Isbn)
	return err
}
