// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateScrapResult = `-- name: UpdateScrapResult :exec
UPDATE Books
SET
    Description = $1,
    Recommendation = $2,
    Toc = $3,
    Source = $4,
    Url = $5
WHERE
    isbn = $6
`

type UpdateScrapResultParams struct {
	Description    pgtype.Text
	Recommendation pgtype.Text
	Toc            pgtype.Text
	Source         pgtype.Text
	Url            pgtype.Text
	Isbn           pgtype.Text
}

func (q *Queries) UpdateScrapResult(ctx context.Context, arg UpdateScrapResultParams) error {
	_, err := q.db.Exec(ctx, updateScrapResult,
		arg.Description,
		arg.Recommendation,
		arg.Toc,
		arg.Source,
		arg.Url,
		arg.Isbn,
	)
	return err
}

const updateVectorSearch = `-- name: UpdateVectorSearch :exec

UPDATE books SET vectorsearch = $1 WHERE isbn = $2
`

type UpdateVectorSearchParams struct {
	Vectorsearch pgtype.Bool
	Isbn         pgtype.Text
}

func (q *Queries) UpdateVectorSearch(ctx context.Context, arg UpdateVectorSearchParams) error {
	_, err := q.db.Exec(ctx, updateVectorSearch, arg.Vectorsearch, arg.Isbn)
	return err
}
