// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.1
// source: libra-data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isbn          string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingVector) Reset() {
	*x = EmbeddingVector{}
	mi := &file_libra_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingVector) ProtoMessage() {}

func (x *EmbeddingVector) ProtoReflect() protoreflect.Message {
	mi := &file_libra_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingVector.ProtoReflect.Descriptor instead.
func (*EmbeddingVector) Descriptor() ([]byte, []int) {
	return file_libra_data_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingVector) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *EmbeddingVector) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type BookRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Isbn            string                 `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author          string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publisher       string                 `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublicationYear string                 `protobuf:"bytes,5,opt,name=publicationYear,proto3" json:"publicationYear,omitempty"`
	SetIsbn         string                 `protobuf:"bytes,6,opt,name=setIsbn,proto3" json:"setIsbn,omitempty"`
	Volume          string                 `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	ClassNum        string                 `protobuf:"bytes,8,opt,name=classNum,proto3" json:"classNum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookRow) Reset() {
	*x = BookRow{}
	mi := &file_libra_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRow) ProtoMessage() {}

func (x *BookRow) ProtoReflect() protoreflect.Message {
	mi := &file_libra_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRow.ProtoReflect.Descriptor instead.
func (*BookRow) Descriptor() ([]byte, []int) {
	return file_libra_data_proto_rawDescGZIP(), []int{1}
}

func (x *BookRow) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *BookRow) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRow) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookRow) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *BookRow) GetPublicationYear() string {
	if x != nil {
		return x.PublicationYear
	}
	return ""
}

func (x *BookRow) GetSetIsbn() string {
	if x != nil {
		return x.SetIsbn
	}
	return ""
}

func (x *BookRow) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *BookRow) GetClassNum() string {
	if x != nil {
		return x.ClassNum
	}
	return ""
}

type BookRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookRow             `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRows) Reset() {
	*x = BookRows{}
	mi := &file_libra_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRows) ProtoMessage() {}

func (x *BookRows) ProtoReflect() protoreflect.Message {
	mi := &file_libra_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRows.ProtoReflect.Descriptor instead.
func (*BookRows) Descriptor() ([]byte, []int) {
	return file_libra_data_proto_rawDescGZIP(), []int{2}
}

func (x *BookRows) GetBooks() []*BookRow {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_libra_data_proto protoreflect.FileDescriptor

var file_libra_data_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x43, 0x0a, 0x0f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0xe1, 0x01, 0x0a, 0x07,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x49, 0x73, 0x62, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x74, 0x49, 0x73, 0x62, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x22,
	0x2d, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x6f, 0x77, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libra_data_proto_rawDescOnce sync.Once
	file_libra_data_proto_rawDescData = file_libra_data_proto_rawDesc
)

func file_libra_data_proto_rawDescGZIP() []byte {
	file_libra_data_proto_rawDescOnce.Do(func() {
		file_libra_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_libra_data_proto_rawDescData)
	})
	return file_libra_data_proto_rawDescData
}

var file_libra_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libra_data_proto_goTypes = []any{
	(*EmbeddingVector)(nil), // 0: pb.EmbeddingVector
	(*BookRow)(nil),         // 1: pb.BookRow
	(*BookRows)(nil),        // 2: pb.BookRows
}
var file_libra_data_proto_depIdxs = []int32{
	1, // 0: pb.BookRows.books:type_name -> pb.BookRow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libra_data_proto_init() }
func file_libra_data_proto_init() {
	if File_libra_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libra_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libra_data_proto_goTypes,
		DependencyIndexes: file_libra_data_proto_depIdxs,
		MessageInfos:      file_libra_data_proto_msgTypes,
	}.Build()
	File_libra_data_proto = out.File
	file_libra_data_proto_rawDesc = nil
	file_libra_data_proto_goTypes = nil
	file_libra_data_proto_depIdxs = nil
}
